name = "kami-website"
main = "worker.js"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
