name = "kami-website"
compatibility_date = "2026-02-24"
account_id = "30a113a636e7792fb845964f984173e5"

routes = [
  { pattern = "kami.mystic.cat", custom_domain = true }
]

[assets]
directory = "./out"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
